// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdhCPo59mzTi7CGHL-Haoc_zsH4xPlVC8',
    appId: '1:714063615662:web:23827549feb85b542f3f3f',
    messagingSenderId: '714063615662',
    projectId: 'appreminder-4a06d',
    authDomain: 'appreminder-4a06d.firebaseapp.com',
    storageBucket: 'appreminder-4a06d.firebasestorage.app',
    measurementId: 'G-6Z6J7MV0D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiMhnsg1RTFb4OzzpF28BcwPifeAvyGvM',
    appId: '1:714063615662:android:0f815acd87d857de2f3f3f',
    messagingSenderId: '714063615662',
    projectId: 'appreminder-4a06d',
    storageBucket: 'appreminder-4a06d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdhCPo59mzTi7CGHL-Haoc_zsH4xPlVC8',
    appId: '1:714063615662:web:ee5f2f55953b745c2f3f3f',
    messagingSenderId: '714063615662',
    projectId: 'appreminder-4a06d',
    authDomain: 'appreminder-4a06d.firebaseapp.com',
    storageBucket: 'appreminder-4a06d.firebasestorage.app',
    measurementId: 'G-W405VL847Z',
  );
}
